// 慢病升级 步骤4：随访模板 + 排期 + 幂等重算。
import 'package:drift/drift.dart' show Value;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:health_archive/data/app_database.dart';
import 'package:health_archive/data/health_repository.dart';
import 'package:health_archive/models/followup_template.dart';
import 'package:health_archive/services/followup_scheduler.dart';

final _now = DateTime(2026, 8, 30);

Disease _disease(String code, {DateTime? found}) => Disease(
      id: code.hashCode & 0x7fffffff,
      profileId: 1,
      name: code,
      status: '当前存在',
      createdAt: _now,
      conditionCode: code,
      foundDate: found,
    );

HealthMetric _m(String id, {required int daysAgo}) => HealthMetric(
      id: (id.hashCode ^ daysAgo) & 0x7fffffff,
      profileId: 1,
      metricId: id,
      metricName: id,
      value: 1,
      unit: 'x',
      status: '正常',
      bodySystem: '其他',
      measuredAt: _now.subtract(Duration(days: daysAgo)),
      sourceType: 'manual',
      createdAt: _now.subtract(Duration(days: daysAgo)),
      matchType: 'manual',
      verificationStatus: 'user_confirmed',
    );

void main() {
  group('模板字典', () {
    test('模板 conditionCode 不重复；每个模板至少一项；每项 key 在模板内唯一', () {
      final codes = <String>{};
      for (final t in FOLLOWUP_TEMPLATES) {
        expect(codes.add(t.conditionCode), isTrue,
            reason: '${t.conditionCode} 模板重复');
        expect(t.items, isNotEmpty);
        final keys = t.items.map((i) => i.key).toList();
        expect(keys.toSet().length, keys.length,
            reason: '${t.conditionCode} 有重复随访项 key');
      }
    });

    test('followUpTemplateFor', () {
      expect(followUpTemplateFor('type2_diabetes'), isNotNull);
      expect(followUpTemplateFor('overweight'), isNull);
      expect(followUpTemplateFor(null), isNull);
    });
  });

  group('planFollowUps 排期', () {
    test('有最近记录 → 锚点是记录日期 + 间隔', () {
      final planned = planFollowUps(
        chronicDiseases: [_disease('type2_diabetes')],
        metrics: [_m('HBA1C', daysAgo: 30)],
        daily: const [],
        now: _now,
      );
      final hba1c =
          planned.firstWhere((p) => p.itemKey == 'hba1c');
      // 30 天前 + 90 天 = 60 天后
      expect(hba1c.dueDate, _now.add(const Duration(days: 60)));
      expect(hba1c.conditionName, '2型糖尿病');
      expect(hba1c.title, contains('糖化血红蛋白'));
    });

    test('完全没有记录、也没确诊日期 → 从今天起排，第一次到期在一个间隔之后', () {
      final planned = planFollowUps(
        chronicDiseases: [_disease('type2_diabetes')],
        metrics: const [],
        daily: const [],
        now: _now,
      );
      final hba1c = planned.firstWhere((p) => p.itemKey == 'hba1c');
      // 锚点取不到时用「今天」，不再是「今天 - 间隔」——不会一记病就已到期。
      expect(hba1c.dueDate.isAfter(_now), isTrue);
    });

    test('上次已复查时间比记录更近 → 用它当锚点', () {
      final planned = planFollowUps(
        chronicDiseases: [_disease('type2_diabetes')],
        metrics: [_m('HBA1C', daysAgo: 200)],
        daily: const [],
        lastCompletedByKey: {
          'type2_diabetes|hba1c': _now.subtract(const Duration(days: 10)),
        },
        now: _now,
      );
      final hba1c = planned.firstWhere((p) => p.itemKey == 'hba1c');
      expect(hba1c.dueDate, _now.add(const Duration(days: 80)));
    });

    test('无模板的病 → 不产生随访项', () {
      final planned = planFollowUps(
        chronicDiseases: [_disease('overweight')],
        metrics: const [],
        daily: const [],
        now: _now,
      );
      expect(planned, isEmpty);
    });
  });

  group('regenerateFollowUpsForAllProfiles 幂等', () {
    late AppDatabase db;
    late HealthRepository repo;

    setUp(() {
      db = AppDatabase(NativeDatabase.memory());
      repo = HealthRepository(db);
    });
    tearDown(() => db.close());

    test('生成 → 再跑不重复 → 删病后清掉', () async {
      await repo.ensureDefaultPersonProfile();
      await repo.insertDisease(
          name: '2型糖尿病', conditionCode: 'type2_diabetes');

      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      final first = await repo.getFollowUpReminders();
      expect(first, isNotEmpty);
      expect(first.every((r) => r.kind == 'followup' && r.autoGenerated),
          isTrue);
      final count = first.length;

      // 再跑一遍不新增
      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      expect((await repo.getFollowUpReminders()).length, count);

      // 删掉这个病 → 随访项应被撤掉
      final d = (await repo.getAllDiseases()).single;
      await repo.deleteDisease(d.id);
      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      expect(await repo.getFollowUpReminders(), isEmpty);
    });

    test('打勾完成后，新周期到期会自动重新变回待办', () async {
      await repo.ensureDefaultPersonProfile();
      await repo.insertDisease(
          name: '痛风', conditionCode: 'gout');
      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      final ua = (await repo.getFollowUpReminders())
          .firstWhere((r) => r.followUpKey == 'ua');

      // 标记已复查（10 天前）
      await (db.update(db.reminders)..where((t) => t.id.equals(ua.id))).write(
        RemindersCompanion(
            completedAt: Value(_now.subtract(const Duration(days: 10)))),
      );

      // 间隔 90 天，10 天前完成 → 新到期日还在未来 → 保持已完成
      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      var again = (await repo.getFollowUpReminders())
          .firstWhere((r) => r.followUpKey == 'ua');
      expect(again.completedAt, isNotNull);

      // 100 天后再算 → 新周期已到期 → completedAt 清空
      await repo.regenerateFollowUpsForAllProfiles(
          now: _now.add(const Duration(days: 100)));
      again = (await repo.getFollowUpReminders())
          .firstWhere((r) => r.followUpKey == 'ua');
      expect(again.completedAt, isNull);
    });

    test('导出不含自动随访提醒', () async {
      await repo.ensureDefaultPersonProfile();
      await repo.insertDisease(
          name: '痛风', conditionCode: 'gout');
      await repo.regenerateFollowUpsForAllProfiles(now: _now);
      final data = await repo.exportHealthData();
      final reminders = data['reminders'] as List;
      expect(reminders.where((r) => (r as Map)['kind'] == 'followup'),
          isEmpty);
    });
  });
}
