// 03：报告解析 → 器官关联 → 复查闭环。仓库层 + 纯逻辑。
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:health_archive/data/app_database.dart';
import 'package:health_archive/data/health_repository.dart';
import 'package:health_archive/models/report_followup.dart';

void main() {
  late AppDatabase db;
  late HealthRepository repo;

  setUp(() {
    db = AppDatabase(NativeDatabase.memory());
    repo = HealthRepository(db);
  });

  tearDown(() async {
    await db.close();
  });

  Future<int> mkReport({DateTime? date, String type = 'B超'}) => repo.insertReport(
        hospitalName: '深圳市人民医院',
        reportDate: date ?? DateTime(2026, 8, 15),
        reportType: type,
        recognitionStatus: 'confirmed',
      );

  group('报告 ↔ 器官关联', () {
    test('setReportOrgans 覆盖式写入；getReportOrgans / reportIdsForArea 读回', () async {
      await repo.ensureDefaultPersonProfile();
      final id = await mkReport();

      await repo.setReportOrgans(id, ['甲状腺', '肝胆', '甲状腺']); // 去重
      expect((await repo.getReportOrgans(id))..sort(), ['甲状腺', '肝胆']..sort());
      expect(await repo.reportIdsForArea('甲状腺'), [id]);
      expect(await repo.reportIdsForArea('肾脏/泌尿'), isEmpty);

      // 覆盖式：再设一次只留新的
      await repo.setReportOrgans(id, ['肾脏/泌尿']);
      expect(await repo.getReportOrgans(id), ['肾脏/泌尿']);
      expect(await repo.reportIdsForArea('甲状腺'), isEmpty);
    });

    test('空集合 = 清除关联', () async {
      await repo.ensureDefaultPersonProfile();
      final id = await mkReport();
      await repo.setReportOrgans(id, ['心血管']);
      await repo.setReportOrgans(id, const []);
      expect(await repo.getReportOrgans(id), isEmpty);
    });

    test('按当前档案隔离', () async {
      await repo.ensureDefaultPersonProfile();
      final selfReport = await mkReport();
      await repo.setReportOrgans(selfReport, ['甲状腺']);

      final otherId = await repo.insertPersonProfile(displayName: '家属');
      await repo.setActiveProfileId(otherId);
      final otherReport = await mkReport();
      await repo.setReportOrgans(otherReport, ['肝胆']);

      expect(await repo.reportIdsForArea('肝胆'), [otherReport]);
      expect(await repo.reportIdsForArea('甲状腺'), isEmpty); // 别人的看不到

      await repo.setActiveProfileId(HealthRepository.defaultProfileId);
      expect(await repo.reportIdsForArea('甲状腺'), [selfReport]);
      expect(await repo.reportIdsForArea('肝胆'), isEmpty);
    });
  });

  group('复查任务：来源 / 器官 / 建议日期', () {
    test('insertReminder 带 sourceType / areaName / recommendedDate，读回一致', () async {
      await repo.ensureDefaultPersonProfile();
      final due = DateTime(2026, 11, 15);
      await repo.insertReminder(
        kind: 'recheck',
        title: '复查 B超',
        sourceType: 'report',
        areaName: '甲状腺',
        dueDate: due,
        recommendedDate: due,
      );
      final r = (await repo.getActiveReminders()).single;
      expect(r.sourceType, 'report');
      expect(r.areaName, '甲状腺');
      expect(r.recommendedDate, due);
      expect(recheckSourceLabel(r.sourceType), '报告建议');
    });

    test('默认来源是 user', () async {
      await repo.ensureDefaultPersonProfile();
      await repo.insertReminder(
        kind: 'recheck',
        title: '复查 尿酸',
        dueDate: DateTime(2026, 10, 1),
      );
      expect((await repo.getActiveReminders()).single.sourceType, 'user');
    });

    test('markReminderCompleted 可指定完成日期', () async {
      await repo.ensureDefaultPersonProfile();
      final id = await repo.insertReminder(
        kind: 'recheck',
        title: '复查 甲功',
        dueDate: DateTime(2026, 11, 1),
      );
      final when = DateTime(2026, 10, 20);
      await repo.markReminderCompleted(id, at: when);
      final r = (await repo.getActiveReminders(includeCompleted: true)).single;
      expect(r.completedAt, when);
    });
  });

  group('findFollowUpMatch（§17）', () {
    Reminder mkRem({
      required String title,
      String? areaName,
      required DateTime due,
      DateTime? completedAt,
      String kind = 'recheck',
    }) =>
        Reminder(
          id: 1,
          profileId: 1,
          kind: kind,
          title: title,
          autoGenerated: false,
          sourceType: 'user',
          areaName: areaName,
          enabled: true,
          dueDate: due,
          completedAt: completedAt,
          createdAt: DateTime(2026, 1, 1),
          updatedAt: DateTime(2026, 1, 1),
        );

    test('器官对得上 + 时间合理 → 命中', () {
      final m = findFollowUpMatch(
        [mkRem(title: '复查 甲功', areaName: '甲状腺', due: DateTime(2026, 11, 1))],
        reportAreas: {'甲状腺'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m, isNotNull);
    });

    test('器官对不上 → 不命中', () {
      final m = findFollowUpMatch(
        [mkRem(title: '复查 甲功', areaName: '甲状腺', due: DateTime(2026, 11, 1))],
        reportAreas: {'肝胆'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m, isNull);
    });

    test('时间差太大 → 不命中', () {
      final m = findFollowUpMatch(
        [mkRem(title: '复查 甲功', areaName: '甲状腺', due: DateTime(2027, 6, 1))],
        reportAreas: {'甲状腺'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m, isNull);
    });

    test('已完成的不参与匹配', () {
      final m = findFollowUpMatch(
        [
          mkRem(
              title: '复查 甲功',
              areaName: '甲状腺',
              due: DateTime(2026, 11, 1),
              completedAt: DateTime(2026, 10, 1)),
        ],
        reportAreas: {'甲状腺'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m, isNull);
    });

    test('无 areaName 时靠标题里的部位名兜底', () {
      final m = findFollowUpMatch(
        [mkRem(title: '复查甲状腺功能', due: DateTime(2026, 11, 1))],
        reportAreas: {'甲状腺'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m, isNotNull);
    });

    test('多个候选取到期日最接近报告日期的', () {
      final near = mkRem(
          title: '复查 A', areaName: '甲状腺', due: DateTime(2026, 10, 25));
      final far =
          mkRem(title: '复查 B', areaName: '甲状腺', due: DateTime(2026, 12, 20));
      final m = findFollowUpMatch(
        [far, near],
        reportAreas: {'甲状腺'},
        reportDate: DateTime(2026, 10, 20),
      );
      expect(m!.title, '复查 A');
    });
  });

  group('metricDeltaLine（§19，中性措辞）', () {
    test('上升 / 下降 / 持平', () {
      expect(metricDeltaLine(62, 52, 'U/L'), '较上次 ↑ 10 U/L');
      expect(metricDeltaLine(52, 62, 'U/L'), '较上次 ↓ 10 U/L');
      expect(metricDeltaLine(52, 52, 'U/L'), '较上次持平');
    });

    test('没有上一条 → null', () {
      expect(metricDeltaLine(52, null, 'U/L'), isNull);
    });

    test('绝不出现「好转 / 恶化 / 恢复」这类结论词', () {
      final samples = [
        metricDeltaLine(10, 5, ''),
        metricDeltaLine(5, 10, 'mmol/L'),
        metricDeltaLine(3.14, 2.71, '%'),
      ];
      for (final s in samples) {
        expect(s, isNotNull);
        expect(s, isNot(contains('好转')));
        expect(s, isNot(contains('恶化')));
        expect(s, isNot(contains('恢复')));
        expect(s, isNot(contains('改善')));
      }
    });
  });

  group('安全规则', () {
    test('保存异常指标不会自动建疾病（Case 2）', () async {
      await repo.ensureDefaultPersonProfile();
      final rid = await mkReport(type: '生化检查');
      await repo.insertMetric(
        metricId: 'FPG',
        metricName: '空腹血糖',
        value: 7.8,
        unit: 'mmol/L',
        referenceMin: 3.9,
        referenceMax: 6.1,
        status: '偏高',
        bodySystem: '血糖代谢',
        measuredAt: DateTime(2026, 8, 15),
        reportId: rid,
      );
      expect(await repo.getAllDiseases(), isEmpty);
    });
  });
}
